/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ConexionMySql;
import Controlador.ControladorTareas;
import Controlador.ControladorUsuarios;
import Modelo.Usuario;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Medac
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private ConexionMySql conexion;
    private ConexionMySql conexion2;
    ArrayList <Usuario> lista;
    ControladorUsuarios controlador;
    ControladorTareas controlador2;
    
    public VentanaPrincipal() throws SQLException {
        initComponents();
        this.setSize(578, 448);
        conexion=new ConexionMySql("root"," ","tareator");
       
        //Bombilla y añadimos el throws.
        conexion.conector();
    }
    /**
     * Creates new form VentanaPrincipal
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 3, 114));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(161, 3, 3));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTRASEÑA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 210, 230, 40);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(270, 210, 140, 40);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(230, 120, 140, 40);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("NUEVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 370, 160, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(161, 3, 3));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USUARIO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 120, 140, 40);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("ACEPTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 290, 140, 30);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("? CONTRASEÑA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(400, 320, 160, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controlador=new ControladorUsuarios(conexion);
        boolean usuarioEncontrado = false;
        boolean contraseñaCorrecta = false;
        
        try{
            lista=controlador.ObtenTodosUsuarios();
             for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getUsuario().equalsIgnoreCase(jTextField1.getText())) {
                usuarioEncontrado=true;
                if (lista.get(i).getContraseña().equalsIgnoreCase(jTextField2.getText())) {
                    contraseñaCorrecta=true;
                    
                i=lista.size();
                }
            }            
        }
             if(usuarioEncontrado){
                 if(contraseñaCorrecta){
                     controlador2=new ControladorTareas(conexion);
                     VentanaTareas v4=new VentanaTareas(conexion);
                     v4.setVisible(true);
                 }
                 else{
                     JOptionPane.showMessageDialog(this, "Contraseña Incorrecta");
                 }
             }
             else{
                 JOptionPane.showMessageDialog(this, "Usuario inexistente");
             }
        }
        catch(SQLException e){
                    e.printStackTrace();
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String r = JOptionPane.showInputDialog(null,"Introduce tu usuario", "Visca el Barça", JOptionPane.OK_CANCEL_OPTION);
       String r2 = JOptionPane.showInputDialog(null,"Introduce tu email", "Visca el Barça", JOptionPane.OK_CANCEL_OPTION);
       try{
           lista = controlador.ObtenTodosUsuarios();
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getUsuario().equalsIgnoreCase(r) && lista.get(i).getEmail().equalsIgnoreCase(r2)) {
                JOptionPane.showMessageDialog(null, "tu contraseña es" + lista.get(i).getContraseña(), "Contraseña", JOptionPane.INFORMATION_MESSAGE);
            }
        }
       } catch(SQLException e){
                    e.printStackTrace();
                    } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
          conexion.conector();

      } catch (SQLException ex) {
          ex.getMessage();
      }
        
        try {
          VentanaCrear v2 = new VentanaCrear(conexion);
          v2.setVisible(true);
          v2.setSize(578, 448);
      } catch (SQLException ex) {
          Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
